#pragma once

#undef PRODUCT
#define PRODUCT Nicky\x0027s Alpha28

#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD_PER_KEY
// #define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

#define TAPPING_TERM 175
#define TAPPING_TERM_PER_KEY
#define COMBO_TERM 60

// #define USB_POLLING_INTERVAL_MS 1
// #define QMK_KEYS_PER_SCAN 12

// #undef DEBOUNCE
// #define DEBOUNCE 8
