#pragma once

#ifdef AUDIO_ENABLE
  #define STARTUP_SONG SONG(PLANCK_SOUND)
#endif

#ifdef MOUSEKEY_ENABLE
  #define MOUSEKEY_DELAY 300
  #define MOUSEKEY_INTERVAL 16
  #define MOUSEKEY_MAX_SPEED 8
  #define MOUSEKEY_TIME_TO_MAX 20
  #define MOUSEKEY_WHEEL_MAX_SPEED 8
  #define MOUSEKEY_WHEEL_TIME_TO_MAX 40
#endif
